### ISSUE TITLE
state doesn't change from home to not_home

### ISSUE THREAD

**Issue by cingolo** [iMicknl/ha-sagemcom-fast#3]
Environment:
Sagemcom F@st 3865bProximus (b-box3)
Release: 8c.514A
GUI Version
7.4.2.0

The state of my tracked device doesn;t change from 'home' to 'not_home'. if i turn off the wifi it keeps the home state then if i reload the integration the Mobile device entity it shows up as 'This entity is not currently available.'

I need to spend some time to investigate why i cannot get the logs and i will have a look into the code. Any other ideas how can debug your application? HA Core is running over docker in Synology For your reference here we have the my config file. 

```
default_config:
frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
logger:
  default: critical
  logs:
    custom_components.sagemcom_fast: debug
```
